FROM node:18 AS build
WORKDIR /app
COPY FRONT/package*.json ./
RUN npm install
COPY FRONT/ .
RUN npm run build --prod

FROM nginx:alpine
COPY --from=build /app/dist/front/browser/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]