FROM python:3.11-slim
WORKDIR /app
COPY DjangoRestApisPostgreSQL/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY DjangoRestApisPostgreSQL/ .
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "DjangoRestApisPostgreSQL.wsgi:application"]